## Lists

In [2]:
mylist = [] # This is an empty list. Lists are the most basic mutable type, and 
            #   are what you should use anytime you will need to add or remove things.
            #   They can hold any combination of any type of object, including
            #   other lists.
mylist.append('to wong foo') # this appends a string
mylist.append([3,5,7]) # this appends a list of numbers
print(mylist)

['to wong foo', [3, 5, 7]]


In [3]:
# Because lists are mutable, you can assign to them and there are methods which 
#   alter them in-place.
mylist[1] = 'is a great movie'
mylist.reverse()
# Addition concatenates lists
print(mylist+[0,0,0,0,0])

['is a great movie', 'to wong foo', 0, 0, 0, 0, 0]


## Tuples

In [4]:
mytup = (1,(2,3),'wow') # Tuples are immutable container types. They are just
                        #   like lists, but they can't be changed once created.
                        #   So: no appending or assignment!

print(mytup)
print(mytup[2][1])
# These are useful if you want to be sure the contents don't change.

(1, (2, 3), 'wow')
o


## Strings

In [5]:
spam = 'Have some spam.' # This is a string. It's an immutable type.
eggs = "Have some eggs." # You can use double or single quotes for strings
                         
print(spam) # Prints the string to the terminal and starts a new line.

Have some spam.


In [6]:
# Remember that Python is base 0.
# Like lists and tuples, strings are "iterables". You can index into them.
# All intervals in Python include the left endpoint and exclude the right one.
# Also: addition concatenates strings
print(spam[0:5] + spam[:10])

Have Have some 


In [7]:
# You can use indexing to go through iterables in different ways
print(eggs[1:10:2])
print(eggs[::-1])

aesm 
.sgge emos evaH


In [8]:
# You can use the format property of a string to replace {} with text, etc.
pirate_call = 'The pirate says {}, {}!!!'.format(2+5,'win')
print(pirate_call)

The pirate says 7, win!!!


## Dictionaries

In [9]:
mydict = {} # This is an empty dict. It's mutable.
            #   Dicts are made up of key-value pairs. Keys can be any immutable,
            #   and they point to a value which can be any object.
            #   While they are iterable (you can iterate through them using 
            #   techniques TBD later), they are NOT ordered in any way.
mydict['color'] = 'blue' # color points to 'blue'
mydict['number'] = 3 # 'number' points to 3
print(mydict)
print(mydict['color'])

{'color': 'blue', 'number': 3}
blue


## Numpy Arrays

In [27]:
import numpy as np
# (Nearly) everything in NumPy uses the array datatype.
# It is mutable, but has a fixed shape and should only contain a single datatype
#   (usually numbers, and most usually floating point numbers)
# You can create an array out of a list, or a list of lists.
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 array of integers
print(f'A = {A}')
print(A[1,0])
print(A[0,:])

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
4
[1 2 3]


In [34]:
# Arrays have a number of attributes
print(A.shape)
x,y = A.shape
print(f'The shape of A is {x} by {y}.')
A.any()==1 #does any entry in A equal 1

#"shallow copy"
#B = A
#B[0,0] = -1
#print(B)
#print(A) #note that A also changes 


#"deep copy"
B=A.copy()
#B[0,0] = -1
print(B)
print(A)

#Checking is A and B are equivalent in their data
(A == B).all() #comparing is A and B are the same at each entry 

#Checking is the memory address of A and B are the same 
A is B 

(3, 3)
The shape of A is 3 by 3.
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


False

In [35]:
# There are a number of routines to create arrays.
#  NOTE: Arrays must be created with a certain shape and maintain that shape.
#  Any change to the shape is essentially destroying the array and recreating it from scratch.
#  Often, an array of zeros is created and then filled in later.
myarray = np.zeros((4,5))
print(myarray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
# Arrays can be of any dimension
array3 = np.ones((4,3,2))

In [37]:
B = np.random.rand(3,3) # 3x3 array of floating point numbers between 0 and 1
print(f'B = {B}')

B = [[0.53389323 0.18558238 0.21486629]
 [0.03113901 0.59148126 0.47721249]
 [0.3482893  0.73510973 0.53415233]]


In [38]:
# All operations are elementwise.
print('Element-wise multiplication:')
print(A*B)

Element-wise multiplication:
[[0.53389323 0.37116477 0.64459887]
 [0.12455603 2.95740628 2.86327494]
 [2.43802513 5.88087785 4.80737097]]


In [39]:
# In Python 3.5+, we also have @ which is matrix multiplication
print('Matrix multiplicaton:')
print(A@B)
# That doesn't always work well for matrix-vector multiplication, 
#   because vectors are typically rows (Python is a row-major language).
#   Instead, use np.dot
v = np.array([2,1,2])
print(np.dot(A,v))

Matrix multiplicaton:
[[ 1.64103916  3.57387409  2.77174826]
 [ 4.38100378  8.1103942   6.45044159]
 [ 7.12096841 12.64691432 10.12913491]]
[10 25 40]


In [ ]:
# Tons of other routines can be found in the numpy library. The docs are fantastic!!